[build-system]
requires = ["setuptools>=58.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88
ignore = [
    "F401", # https://docs.astral.sh/ruff/rules/unused-import/
    "E741", # https://docs.astral.sh/ruff/rules/ambiguous-variable-name/
    "E402", # https://docs.astral.sh/ruff/rules/module-import-not-at-top-of-file/
    "E712",
    "F541", # https://docs.astral.sh/ruff/rules/f-string-missing-placeholders/
    "E713", # https://docs.astral.sh/ruff/rules/not-in-test/
    "F841", # https://docs.astral.sh/ruff/rules/unused-variable/
    "E731", # https://docs.astral.sh/ruff/rules/lambda-assignment/
    "F402"
]

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
required_plugins = [
    "pytest-xdist",
    "pytest-env>=0.6"
]
env = [
    "SKYPILOT_DEBUG=1",
    "SKYPILOT_DISABLE_USAGE_COLLECTION=1"
]
addopts = "-s -n 16 -q --tb=short --dist loadgroup --disable-warnings"

[tool.mypy]
python_version = "3.8"
follow_imports = "skip"
ignore_missing_imports = true
allow_redefinition = true

[tool.isort]
profile = "google"
line_length = 80
multi_line_output = 0
combine_as_imports = true
use_parentheses = true
